    class Valves(BaseModel):
        ANTHROPIC_API_KEY: str = Field(
            default="",
            description="Anthropic API key (pay-per-token). Leave empty to use the subscription OAuth token or inherit from the backend env.",
        )
        CLAUDE_CODE_OAUTH_TOKEN: str = Field(
            default="",
            description=(
                "Long-lived Claude Pro/Max/Team OAuth token generated by "
                "`claude setup-token` on a machine with a browser. When set, "
                "bills against your subscription (not the API). Takes priority "
                "over ANTHROPIC_API_KEY — the key gets unset so it can't "
                "override. Anthropic's terms: use your own subscription only, "
                "don't re-offer subscription auth to end users."
            ),
        )
        MODEL: str = Field(
            default="claude-haiku-4-5",
            description="Claude model ID (e.g. claude-haiku-4-5, claude-sonnet-4-6, claude-opus-4-7).",
        )
        MODELS: str = Field(
            default="",
            description=(
                "Comma-separated EXTRA Claude model IDs to expose as separate "
                "picker entries (e.g. claude-haiku-4-5,claude-opus-4-8). Each "
                "gets its own model named by ID; the base entry still uses MODEL."
            ),
        )
        INLINE_TOOL_DETAILS: bool = Field(
            default=True,
            description=(
                "Render tool inputs/thinking as inline <details> blocks in the "
                "message text. The web UI shows these as collapsibles, but some "
                "mobile clients (e.g. Conduit) render the raw tags as text - "
                "set False there; tool activity still appears via status events."
            ),
        )
        PERMISSION_MODE: str = Field(
            default="bypassPermissions",
            description='Permission mode: "default", "acceptEdits", "bypassPermissions", "plan", or "dontAsk".',
        )
        ALLOWED_TOOLS: str = Field(
            default="Read,Write,Edit,Bash,Glob,Grep,WebSearch,WebFetch",
            description="Comma-separated tools auto-approved without prompting.",
        )
        WORKDIR_ROOT: str = Field(
            default="/tmp/claude-agent-pipe",
            description="Root directory for per-chat workspaces. One subdir per chat_id.",
        )
        GATEWAY_CONTRACT_PATH: str = Field(
            default="",
            description=(
                "Path to a rules file (e.g. ~/gateway/AGENTS.md) appended to "
                "the system prompt when a chat is rooted "
                "outside WORKDIR_ROOT (a #repo: session), where the agent would "
                "otherwise load only that repo's CLAUDE.md and never see the "
                "gateway's Hard Rules. Empty disables the append."
            ),
        )
        MAX_TURNS: int = Field(
            default=30,
            description="Maximum agent turns per user message. 0 disables the cap.",
        )
        CONTEXT_WINDOW_TOKENS: int = Field(
            default=200_000,
            description=(
                "FALLBACK context window (tokens) for the post-turn "
                "'Done · context X/Y (N%)' status line, used only when the "
                "SDK's live context query fails (which otherwise supplies the "
                "real per-model window). 0 disables the fallback suffix."
            ),
        )
        EFFORT: str = Field(
            default="",
            description=(
                "Default effort level for agent turns: low|medium|high|xhigh|"
                "max. Empty = SDK default (high). A message starting with "
                "'/effort <level>' overrides it for that turn."
            ),
        )
        TASK_BUDGET_TOKENS: int = Field(
            default=0,
            description=(
                "Per-turn token budget the model is made aware of and paces "
                "itself against (output_config.task_budget). API minimum is "
                "20000 — smaller nonzero values are ignored. 0 disables."
            ),
        )
        FALLBACK_MODEL: str = Field(
            default="",
            description=(
                "Model to retry with if the primary model fails or is "
                "unavailable (SDK fallback_model). Empty disables."
            ),
        )
        MAX_BUFFER_MB: int = Field(
            default=32,
            description=(
                "Maximum size (MiB) of a single stream-json message read back "
                "from the Claude Code CLI. The SDK's own default is 1 MiB, "
                "which a Read of any attachment over ~780 KiB blows past once "
                "base64 expansion (~1.34x) and the JSON envelope are counted — "
                "killing the message reader mid-response. 32 MiB clears the "
                "10 MiB image-attachment cap with room to spare and matches "
                "the Anthropic API's own 32 MB request-body ceiling, so the "
                "framer stops rejecting payloads the API would have accepted. "
                "0 falls back to the SDK default."
            ),
        )
        SETTING_SOURCES: str = Field(
            default="",
            description=(
                "Comma-separated Claude Code setting sources to load: any of "
                '"user", "project", "local". Empty (default) loads NONE — each '
                "chat runs from a clean baseline and does NOT inherit the "
                "backend user's ~/.claude/ or the workdir's .claude/ config. "
                'Add "user" to load ~/.claude/CLAUDE.md and ~/.claude/'
                "settings.json (persistent context for single-user "
                "setups). WARNING: settings.json can define hooks that execute "
                "code and permission grants — only enable on instances you "
                "trust and control. Avoid on multi-user/public deployments."
            ),
        )
        REPO_MAP: str = Field(
            default="",
            description=(
                "Comma-separated name=path allowlist of repos a chat may run "
                "in, e.g. app=/srv/app,notes=/home/me/notes. Start a chat's "
                "FIRST message with #repo:<name> to set its cwd to that path "
                "for the whole chat (loads the repo's CLAUDE.md via the "
                "project setting source). Unknown names error in-chat. Empty "
                "disables the feature. Grants nothing new — bypassPermissions "
                "already reaches these paths; this only controls cwd."
            ),
        )

    def __init__(self) -> None:
        self.valves = self.Valves()

    def pipes(self) -> List[Dict[str, str]]:
        entries = [{"id": "claude-code", "name": "Claude Code"}]
        for m in [m.strip() for m in self.valves.MODELS.split(",") if m.strip()]:
            entries.append({"id": f"claude-code-{m}", "name": f"Claude Code ({m})"})
        return entries

    def _resolve_model(self, body: Optional[Dict[str, Any]]) -> str:
        return _model_from_requested(
            str((body or {}).get("model") or ""), self.valves.MODEL
        )

    async def _run_fast(
        self,
        body: Dict[str, Any],
        user_dict: Optional[Dict[str, Any]],
        metadata: Optional[Dict[str, Any]],
        files: Optional[List[Dict[str, Any]]],
        event_emitter: Optional[Callable],
    ) -> AsyncGenerator[str, None]:
        """Dispatcher. Pick the cheapest available fast path:
        1. API key available → direct Messages API (~300 ms – 2 s).
        2. OAuth token only → "lite agent": ClaudeSDKClient with no tools,
           no MCP, plain system prompt (~2–3 s; CLI cold-start is
           unavoidable because Anthropic's Messages API rejects OAuth tokens
           — the subscription only works via the Claude Code backend).
        """
        has_api_key = bool(
            self.valves.ANTHROPIC_API_KEY or os.environ.get("ANTHROPIC_API_KEY")
        )
        if has_api_key:
            async for chunk in self._run_messages_api(
                body, user_dict, metadata, files, event_emitter
            ):
                yield chunk
        else:
            async for chunk in self._run_lite_agent(
                body, user_dict, metadata, files, event_emitter
            ):
                yield chunk

    async def _run_messages_api(
        self,
        body: Dict[str, Any],
        user_dict: Optional[Dict[str, Any]],
        metadata: Optional[Dict[str, Any]],
        files: Optional[List[Dict[str, Any]]],
        event_emitter: Optional[Callable],
    ) -> AsyncGenerator[str, None]:
        """Direct Anthropic Messages-API streaming with optional agentic KB
        tool use. No CLI cold start, no Claude Code persona. If a Workspace
        Model has a knowledge base attached, Claude gets the same KB tools
        as the full agent (search / list / read / grep) and can reformulate
        queries in a native tool-use loop."""
        try:
            from anthropic import AsyncAnthropic
        except ImportError:
            yield "_Fast path needs the `anthropic` package — add it to the Function requirements._"
            return

        if self.valves.ANTHROPIC_API_KEY:
            client = AsyncAnthropic(api_key=self.valves.ANTHROPIC_API_KEY)
        else:
            client = AsyncAnthropic()

        system_parts: List[str] = []
        ws_system = _extract_system_prompt(body)
        if ws_system:
            system_parts.append(ws_system)
        system = "\n\n".join(p for p in system_parts if p.strip()) or None

        # Build KB tools if a workspace knowledge base is attached. Both the
        # MCP server's tool handlers and the Anthropic tool defs come from
        # the same underlying closures (via _build_kb_mcp_server's 3rd
        # return), so Claude sees an identical toolbox in either fast or
        # agent mode.
        knowledge = _knowledge_collections(metadata, files)
        kb_row_ids = _knowledge_row_ids(metadata)
        _, _, kb_tools_by_name = _build_kb_mcp_server(
            knowledge,
            knowledge_row_ids=kb_row_ids,
            user_dict=user_dict,
            event_emitter=event_emitter,
        )
        tool_defs = _anthropic_kb_tool_defs(knowledge, bool(kb_row_ids))

        # Conversation: user/assistant only. Strip any `/agent` or `/fast`
        # prefix from user turns so the model doesn't see it as content.
        messages: List[Dict[str, Any]] = []
        for msg in body.get("messages") or []:
            role = msg.get("role")
            if role not in ("user", "assistant"):
                continue
            content = msg.get("content", "")
            if isinstance(content, list):
                content = "\n".join(
                    p.get("text", "")
                    for p in content
                    if isinstance(p, dict) and p.get("type") == "text"
                )
            if role == "user":
                content = _strip_mode_prefix(content)
            if content:
                messages.append({"role": role, "content": content})

        if not messages:
            return

        if event_emitter:
            try:
                await event_emitter(
                    {
                        "type": "status",
                        "data": {"description": "⚡ fast mode", "done": False},
                    }
                )
            except Exception:
                pass

        # Agentic tool-use loop. Stream text as it arrives; if Claude stops
        # with stop_reason="tool_use", execute the tool(s), append the
        # tool_result content blocks, and loop. Cap iterations so a runaway
        # loop can't pin the event loop.
        MAX_TOOL_ROUNDS = 10
        for _round in range(MAX_TOOL_ROUNDS + 1):
            kwargs: Dict[str, Any] = {
                "model": self._resolve_model(body),
                "max_tokens": 4096,
                "messages": messages,
            }
            if system:
                kwargs["system"] = system
            if tool_defs:
                kwargs["tools"] = tool_defs

            try:
                async with client.messages.stream(**kwargs) as stream:
                    async for text in stream.text_stream:
                        yield text
                    final = await stream.get_final_message()
            except Exception as exc:
                log.exception("Fast path failed")
                yield (
                    f"\n\n**Fast-path error:** `{type(exc).__name__}: {exc}`\n"
                )
                return

            if final.stop_reason != "tool_use":
                return  # end_turn — we're done

            # Serialise the assistant message (incl. tool_use blocks) back
            # into the conversation, then resolve each tool call.
            assistant_content: List[Dict[str, Any]] = []
            for block in final.content:
                bt = block.type
                if bt == "text":
                    assistant_content.append({"type": "text", "text": block.text})
                elif bt == "tool_use":
                    assistant_content.append(
                        {
                            "type": "tool_use",
                            "id": block.id,
                            "name": block.name,
                            "input": block.input,
                        }
                    )
            messages.append({"role": "assistant", "content": assistant_content})

            tool_results: List[Dict[str, Any]] = []
            for block in final.content:
                if block.type != "tool_use":
                    continue
                preview = _tool_preview(block.name, block.input or {})
                if event_emitter:
                    try:
                        await event_emitter(
                            {
                                "type": "status",
                                "data": {
                                    "description": f"🔧 {block.name}"
                                    + (f": {preview}" if preview else ""),
                                    "done": False,
                                },
                            }
                        )
                    except Exception:
                        pass
                # Render a compact tool-use note so the user can see what
                # Claude searched for.
                summary = f"🔧 {block.name}" + (f" · {preview}" if preview else "")
                yield (
                    "\n\n<details>\n"
                    f"<summary>{summary}</summary>\n\n"
                    f"{_tool_input_block(block.name, block.input or {})}\n\n"
                    "</details>\n\n"
                )
                text = await _dispatch_kb_tool(
                    block.name, block.input or {}, kb_tools_by_name
                )
                tool_results.append(
                    {
                        "type": "tool_result",
                        "tool_use_id": block.id,
                        "content": text,
                    }
                )
            messages.append({"role": "user", "content": tool_results})

        yield "\n\n_(Fast-path tool loop cap reached — switch to `/agent` for deeper research.)_\n"

    async def _run_lite_agent(
        self,
        body: Dict[str, Any],
        user_dict: Optional[Dict[str, Any]],
        metadata: Optional[Dict[str, Any]],
        files: Optional[List[Dict[str, Any]]],
        event_emitter: Optional[Callable],
    ) -> AsyncGenerator[str, None]:
        """OAuth-compatible fast path: ClaudeSDKClient with KB tools only
        (no Bash / Read / Write / Web / files). Pays the CLI cold-start
        (~1–2 s) but skips the big agent persona. When a workspace knowledge
        base is attached, Claude can agentically search / list / read / grep
        it — query reformulation works here too."""
        prompt = _strip_mode_prefix(_extract_latest_user_prompt(body))
        if not prompt:
            return

        # Workspace-Model system + prior conversation (ClaudeSDKClient.query
        # takes a single string, so we pack history into the system).
        system_parts: List[str] = []
        ws_system = _extract_system_prompt(body)
        if ws_system:
            system_parts.append(ws_system)

        history_lines: List[str] = []
        messages = body.get("messages") or []
        user_turns_remaining = sum(1 for m in messages if m.get("role") == "user")
        consumed = 0
        for msg in messages:
            role = msg.get("role")
            if role not in ("user", "assistant"):
                continue
            content = msg.get("content", "")
            if isinstance(content, list):
                content = "\n".join(
                    p.get("text", "")
                    for p in content
                    if isinstance(p, dict) and p.get("type") == "text"
                )
            if role == "user":
                content = _strip_mode_prefix(content)
                consumed += 1
                if consumed == user_turns_remaining:
                    continue  # skip the latest — it's the query itself
            if content.strip():
                history_lines.append(f"{role.capitalize()}: {content.strip()}")
        if history_lines:
            system_parts.append(
                "Prior conversation (for context):\n\n" + "\n\n".join(history_lines)
            )

        # KB tools via the existing MCP server. No Bash/Read/Write/etc.
        knowledge = _knowledge_collections(metadata, files)
        kb_row_ids = _knowledge_row_ids(metadata)
        kb_server, kb_tool_names, _kb_dict = _build_kb_mcp_server(
            knowledge,
            knowledge_row_ids=kb_row_ids,
            user_dict=user_dict,
            event_emitter=event_emitter,
        )

        if kb_tool_names:
            system_parts.append(
                "You have read-only knowledge-base tools ("
                + ", ".join(t.rsplit("__", 1)[-1] for t in kb_tool_names)
                + "). Use them when the user asks about facts that might be "
                "in the knowledge base. Reformulate and search multiple times "
                "if the first query misses."
            )
        else:
            system_parts.append("Respond concisely and directly.")
        system_text = "\n\n".join(p for p in system_parts if p.strip())

        options_kwargs: Dict[str, Any] = {
            "model": self._resolve_model(body),
            "permission_mode": self.valves.PERMISSION_MODE,
            "allowed_tools": kb_tool_names,
            "setting_sources": _parse_setting_sources(self.valves.SETTING_SOURCES),
            # NOTE: unlike the main loop, this path does not append the
            # gateway contract (_gateway_contract) — it has no cwd of its own
            # and is currently unreachable ("Fast path disabled" below). If
            # routing to it is ever restored, add the append here too, or
            # repo-rooted sessions lose the Hard Rules again.
            "system_prompt": system_text,
            "include_partial_messages": True,
        }
        if self.valves.MAX_BUFFER_MB:
            options_kwargs["max_buffer_size"] = (
                self.valves.MAX_BUFFER_MB * 1024 * 1024
            )
        if kb_server is not None:
            options_kwargs["mcp_servers"] = {"helm-kb": kb_server}
        # No bare chat_id local here (unlike the main loop) — this fast path
        # only has `metadata`, which OWUI populates with the chat id under
        # the "chat_id" key.
        chat_id = (metadata or {}).get("chat_id") or None
        agent_env = _agent_env(chat_id)
        if agent_env:
            options_kwargs["env"] = {**options_kwargs.get("env", {}), **agent_env}
        options = ClaudeAgentOptions(**options_kwargs)

        if event_emitter:
            try:
                await event_emitter(
                    {
                        "type": "status",
                        "data": {
                            "description": "⚡ fast mode (OAuth)",
                            "done": False,
                        },
                    }
                )
            except Exception:
                pass

        thinking_buffers: Dict[int, str] = {}
        # Paragraph break between consecutive assistant text blocks — same
        # rationale as the full agent path (see _pipe_stream's text_emitted).
        text_emitted = False
        try:
            async with ClaudeSDKClient(options=options) as client:
                await client.query(prompt)
                async for message in client.receive_response():
                    if isinstance(message, StreamEvent):
                        ev = message.event or {}
                        etype = ev.get("type")
                        if etype == "message_start":
                            thinking_buffers.clear()
                        elif etype == "content_block_start":
                            block = ev.get("content_block") or {}
                            if block.get("type") == "thinking":
                                thinking_buffers[ev.get("index", 0)] = ""
                            elif block.get("type") == "text" and text_emitted:
                                yield "\n\n"
                        elif etype == "content_block_delta":
                            delta = ev.get("delta") or {}
                            dt = delta.get("type")
                            if dt == "text_delta":
                                text = delta.get("text", "")
                                if text:
                                    text_emitted = True
                                    yield text
                            elif dt == "thinking_delta":
                                idx = ev.get("index", 0)
                                if idx in thinking_buffers:
                                    thinking_buffers[idx] += delta.get("thinking", "")
                        elif etype == "content_block_stop":
                            idx = ev.get("index", 0)
                            if idx in thinking_buffers:
                                text = thinking_buffers.pop(idx).strip()
                                if text and self.valves.INLINE_TOOL_DETAILS:
                                    yield (
                                        "\n\n<details>\n"
                                        "<summary>💭 Thinking</summary>\n\n"
                                        f"{text}\n\n"
                                        "</details>\n\n"
                                    )
                    elif isinstance(message, AssistantMessage):
                        # Tool-use rendering (KB tools only here).
                        for block in message.content:
                            if isinstance(block, ToolUseBlock):
                                preview = _tool_preview(block.name, block.input)
                                summary = f"🔧 {block.name}" + (
                                    f" · {preview}" if preview else ""
                                )
                                if self.valves.INLINE_TOOL_DETAILS:
                                    yield (
                                        "\n\n<details>\n"
                                        f"<summary>{summary}</summary>\n\n"
                                        f"{_tool_input_block(block.name, block.input)}\n\n"
                                        "</details>\n\n"
                                    )
                                elif event_emitter:
                                    try:
                                        await event_emitter({"type": "status", "data": {"description": summary, "done": False}})
                                    except Exception:
                                        pass
                    elif isinstance(message, UserMessage):
                        # Surface tool errors (quietly) so the user isn't
                        # confused by Claude retrying silently.
                        content = message.content
                        if isinstance(content, list):
                            for block in content:
                                if (
                                    isinstance(block, ToolResultBlock)
                                    and block.is_error
                                ):
                                    err_text = _format_tool_result(block.content)[:400]
                                    if self.valves.INLINE_TOOL_DETAILS:
                                        yield (
                                            "\n\n<details>\n<summary>"
                                            "<sub>⚙️ tool hiccup</sub></summary>\n\n"
                                            f"```\n{err_text}\n```\n\n"
                                            "</details>\n\n"
                                        )
                    elif isinstance(message, ResultMessage):
                        return
        except CLIJSONDecodeError:
            log.exception("Lite-agent fast path exceeded the stream-json buffer")
            yield (
                "\n\n**Response too large to read back.** A single message from "
                "the Claude Code CLI exceeded the "
                f"{self.valves.MAX_BUFFER_MB} MiB `MAX_BUFFER_MB` limit — "
                "usually a very large file or image read into the transcript. "
                "Raise `MAX_BUFFER_MB` in the pipe's valves, or work with a "
                "smaller file.\n"
            )
        except Exception as exc:
            log.exception("Lite-agent fast path failed")
            yield f"\n\n**Fast-path error:** `{type(exc).__name__}: {exc}`\n"

    async def pipe(
        self,
        body: Dict[str, Any],
        __chat_id__: Optional[str] = None,
        __event_emitter__: Optional[Callable] = None,
        __files__: Optional[List[Dict[str, Any]]] = None,
        __user__: Optional[Dict[str, Any]] = None,
        __metadata__: Optional[Dict[str, Any]] = None,
    ) -> AsyncGenerator[str, None]:
        """Public entrypoint. Scrubs secrets from everything leaving the pipe.

        Kept as a thin wrapper around `_pipe_stream` so the redaction can't be
        bypassed by a future `yield` added inside the agent loop: both the
        response stream and the status/event channel pass through here.
        OpenWebUI injects the dunder arguments by signature inspection, so
        this wrapper must keep the original parameter list verbatim.
        """
        redactor = _StreamRedactor()
        event_hits: List[str] = []
        emitter = _redacting_emitter(__event_emitter__, event_hits)

        turn_info: Dict[str, Any] = {}
        emitted_parts: List[str] = []

        # No try/finally around this loop: flushing from a `finally` would mean
        # yielding during GeneratorExit if the client disconnects mid-stream,
        # which raises RuntimeError. Dropping a held tail on an aborted stream
        # is the safe direction — it withholds text rather than emitting it.
        async for chunk in self._pipe_stream(
            body, __chat_id__, emitter, __files__, __user__, __metadata__,
            turn_info=turn_info,
        ):
            safe = redactor.feed(chunk)
            if safe:
                if not __chat_id__:
                    emitted_parts.append(safe)
                yield safe

        tail = redactor.flush()
        if tail:
            if not __chat_id__:
                emitted_parts.append(tail)
            yield tail

        # Keyless turn finished cleanly → register its post-turn fingerprint
        # so the NEXT call (whose prefix is this history + this reply) resumes
        # warm. If redaction fired, the client-stored text differs from what
        # the agent produced — the next lookup misses and replays once; safe.
        if not __chat_id__ and turn_info.get("session_id"):
            store = _load_fp_store(self.valves.WORKDIR_ROOT)
            fp = _history_fingerprint(
                (body.get("messages") or [])
                + [{"role": "assistant", "content": "".join(emitted_parts)}]
            )
            # An all-empty normalization must never claim the shared
            # empty-prefix hash that every brand-new keyless chat's cold
            # lookup collides on.
            if fp != _EMPTY_FP:
                store[fp] = {
                    "session_id": turn_info["session_id"],
                    "workdir": turn_info["workdir"],
                    "cwd": turn_info.get("cwd") or turn_info["workdir"],
                    "ts": time.time(),
                }
                _save_fp_store(self.valves.WORKDIR_ROOT, store)

        hits = redactor.hits + event_hits
        if hits:
            # Log the kinds, never the values. A hit means something read a
            # credential into the response path — worth a rotation decision
            # even though the value never reached the chat DB.
            log.warning(
                "pipe output redaction fired: %s",
                ", ".join(f"{k}×{hits.count(k)}" for k in sorted(set(hits))),
            )

    async def _record_usage(
        self,
        usage_payload: Dict[str, int],
        __event_emitter__: Optional[Callable],
        __metadata__: Optional[Dict[str, Any]],
    ) -> None:
        """Publish the turn's usage twice: a chat:completion event for live
        listeners (never persisted), and a direct write to the saved message —
        the socket emitter's save_to_chat branch drops chat:completion, and the
        message's ⓘ popover renders only from the saved `usage`. The upsert
        merges keys, so the middleware's later {'done', 'output'} upsert keeps
        it; isawaitable covers OWUI versions where the upsert is sync. Both
        paths are best-effort: a failure here must not break the turn."""
        if __event_emitter__ is not None:
            try:
                await __event_emitter__(
                    {"type": "chat:completion", "data": {"usage": usage_payload}}
                )
            except Exception:
                log.debug("usage emit failed", exc_info=True)
        try:
            chat_id_meta = (__metadata__ or {}).get("chat_id")
            msg_id_meta = (__metadata__ or {}).get("message_id")
            if chat_id_meta and msg_id_meta:
                from open_webui.models.chats import Chats

                res = Chats.upsert_message_to_chat_by_id_and_message_id(
                    chat_id_meta, msg_id_meta, {"usage": usage_payload}, touch=False
                )
                if inspect.isawaitable(res):
                    await res
        except Exception:
            log.debug("usage DB write failed", exc_info=True)

    async def _pipe_stream(
        self,
        body: Dict[str, Any],
        __chat_id__: Optional[str] = None,
        __event_emitter__: Optional[Callable] = None,
        __files__: Optional[List[Dict[str, Any]]] = None,
        __user__: Optional[Dict[str, Any]] = None,
        __metadata__: Optional[Dict[str, Any]] = None,
        *,
        turn_info: Optional[Dict[str, Any]] = None,
        _no_resume: bool = False,
    ) -> AsyncGenerator[str, None]:
        # Auth selection:
        #   1. If CLAUDE_CODE_OAUTH_TOKEN valve is set → use subscription.
        #      Remove any ANTHROPIC_API_KEY from env because per Claude Code's
        #      precedence order, the API key outranks the OAuth token (docs:
        #      code.claude.com/docs/en/authentication#authentication-precedence)
        #      and would otherwise silently win.
        #   2. Else if ANTHROPIC_API_KEY valve is set → use API.
        #   3. Else → whatever the backend environment already provides.
        if self.valves.CLAUDE_CODE_OAUTH_TOKEN:
            os.environ["CLAUDE_CODE_OAUTH_TOKEN"] = self.valves.CLAUDE_CODE_OAUTH_TOKEN
            os.environ.pop("ANTHROPIC_API_KEY", None)
            os.environ.pop("ANTHROPIC_AUTH_TOKEN", None)
        elif self.valves.ANTHROPIC_API_KEY:
            os.environ["ANTHROPIC_API_KEY"] = self.valves.ANTHROPIC_API_KEY
        # claude CLI refuses --dangerously-skip-permissions under root unless
        # told it's inside a sandbox. OpenWebUI's backend runs as UID 0.
        os.environ.setdefault("IS_SANDBOX", "1")
        # HUB_CHAT_ID reaches the agent exactly one way: `_agent_env` putting it
        # in this client's `ClaudeAgentOptions.env`. `_agent_env` returning `{}`
        # means "inherit", not "guaranteed unset" — so for a caller with no chat
        # id, an ambient HUB_CHAT_ID in Open WebUI's own environment would flow
        # straight through to the agent, and `hub-async.sh` would deliver that
        # session's async result into someone else's conversation. Clearing it
        # here makes the per-client value the only path there is.
        os.environ.pop("HUB_CHAT_ID", None)

        prompt = _extract_latest_user_prompt(body)
        if not prompt:
            yield "_No user message to send to Claude Code._"
            return

        # Fast path disabled — always run the full agent loop.
        prompt = _strip_mode_prefix(prompt)
        repo_name, prompt = _extract_repo_prefix(prompt)
        effort_override, prompt = _extract_effort_prefix(prompt)

        # Keyless callers (no __chat_id__ — generic OpenAI-API clients such
        # as Conduit or voice integrations don't send OWUI's proprietary
        # top-level `chat_id` field) get session identity from a fingerprint
        # of the conversation prefix rather than from chat_id — see the
        # block below. A cold start (first turn, or a fingerprint miss: new
        # chat, edited message, pruned entry) replays the full
        # body["messages"] history as a transcript once, then resumes warm.
        # Keyed callers (native UI) keep session resume; on a cold start
        # (map entry lost, e.g. after an OWUI restart) they too replay
        # history once, then resume warm from the new session.
        chat_id = __chat_id__ or None
        # Keyless callers (Conduit, generic OpenAI-API clients) get session
        # identity by fingerprinting the conversation prefix. Hit → resume
        # that session in its own workdir (warm, tool results intact).
        # Miss (new chat, edited message) → fresh uuid workdir, replay once,
        # register after the turn. This also retires the old shared
        # "default" workdir where all keyless chats collided.
        fp_entry: Optional[Dict[str, Any]] = None
        if chat_id:
            workdir = Path(self.valves.WORKDIR_ROOT) / chat_id
        else:
            fp_entry = _load_fp_store(self.valves.WORKDIR_ROOT).get(
                _history_fingerprint(
                    _strip_latest_user(body.get("messages") or [])
                )
            )
            if fp_entry and not fp_entry.get("workdir"):
                # Malformed/partial entry — treat as a miss rather than
                # trusting a workdir (or session_id) that isn't there.
                fp_entry = None
            if fp_entry:
                workdir = Path(fp_entry["workdir"])
            else:
                workdir = (
                    Path(self.valves.WORKDIR_ROOT)
                    / f"anon-{uuid.uuid4().hex[:12]}"
                )
        workdir.mkdir(parents=True, exist_ok=True)

        # cwd: persisted repo choice wins; else an explicit #repo: prefix on
        # a fresh session; else the scratch workdir. Metadata lives under
        # WORKDIR_ROOT regardless — never inside a repo.
        repo_map = _parse_repo_map(self.valves.REPO_MAP)
        cwd = Path(
            (
                _load_session_meta(self.valves.WORKDIR_ROOT, chat_id).get("cwd")
                if chat_id
                else (fp_entry or {}).get("cwd")
            )
            or workdir
        )
        if repo_name is not None:
            if repo_name not in repo_map:
                allowed = ", ".join(sorted(repo_map)) or "(none configured)"
                yield (
                    f"_Unknown repo `{repo_name}`. Allowed: {allowed}._"
                )
                return
            target = Path(repo_map[repo_name])
            if not target.is_dir():
                yield f"_Repo path for `{repo_name}` does not exist on the host._"
                return
            if chat_id:
                has_session = bool(
                    _chat_sessions.get(chat_id)
                    or _load_session_meta(self.valves.WORKDIR_ROOT, chat_id).get(
                        "session_id"
                    )
                )
            else:
                has_session = bool(fp_entry and fp_entry.get("session_id"))
            if has_session and cwd != target:
                # A live session already exists for this chat; Claude Code
                # sessions are per-directory, so switching mid-chat can't
                # resume. Tell the user instead of silently degrading.
                yield (
                    "_This chat already runs in another directory; `#repo:` "
                    "only takes effect on a chat's first message. Start a "
                    "new chat._"
                )
                return
            cwd = target

        allowed_tools = [
            t.strip() for t in self.valves.ALLOWED_TOOLS.split(",") if t.strip()
        ]
        # In-process map is a cache; the meta file survives OWUI restarts,
        # pipe redeploys, and valve edits.
        resume_id: Optional[str] = None
        if not _no_resume:
            if chat_id:
                resume_id = _chat_sessions.get(chat_id) or _load_session_meta(
                    self.valves.WORKDIR_ROOT, chat_id
                ).get("session_id")
            elif fp_entry:
                resume_id = fp_entry.get("session_id")

        # Image attachments on the latest user message: OWUI delivers them as
        # image_url content parts, which the text-only prompt extraction
        # drops. Write them to files under the workdir and reference the
        # paths in the prompt so the agent can Read them.
        attachment_notes = _save_image_attachments(body, workdir)
        if attachment_notes:
            prompt = prompt + "\n\n" + "\n".join(attachment_notes)

        if resume_id is None:
            prompt = _render_transcript(body, prompt)

        # Knowledge base attached via Workspace Model → expose as an MCP tool
        # Claude can call agentically. OpenWebUI's middleware already added one
        # entry per attached KB to files/__files__.
        kb_server, kb_tool_names, _ = _build_kb_mcp_server(
            _knowledge_collections(__metadata__, __files__),
            knowledge_row_ids=_knowledge_row_ids(__metadata__),
            user_dict=__user__,
            event_emitter=__event_emitter__,
        )
        allowed_tools = allowed_tools + kb_tool_names

        options_kwargs: Dict[str, Any] = {
            "cwd": str(cwd),
            "model": self._resolve_model(body),
            "permission_mode": self.valves.PERMISSION_MODE,
            "allowed_tools": allowed_tools,
            # Which filesystem settings to load (user ~/.claude/, project .claude/,
            # local). Default empty = clean baseline, no inheritance of the backend
            # user's config. Opt in via the SETTING_SOURCES valve (e.g. "user" to
            # load ~/.claude/CLAUDE.md). See the valve's security warning.
            "setting_sources": _parse_setting_sources(self.valves.SETTING_SOURCES),
            # Stream token-level deltas so long answers type out instead of
            # appearing as one chunk when the block finishes.
            "include_partial_messages": True,
        }
        if resume_id:
            options_kwargs["resume"] = resume_id
        if self.valves.MAX_TURNS:
            options_kwargs["max_turns"] = self.valves.MAX_TURNS
        if self.valves.MAX_BUFFER_MB:
            options_kwargs["max_buffer_size"] = (
                self.valves.MAX_BUFFER_MB * 1024 * 1024
            )
        if kb_server is not None:
            options_kwargs["mcp_servers"] = {"helm-kb": kb_server}
        effort = effort_override or self.valves.EFFORT.strip().lower() or None
        if effort in _EFFORT_LEVELS:
            options_kwargs["effort"] = effort
        if self.valves.TASK_BUDGET_TOKENS >= 20_000:
            options_kwargs["task_budget"] = {
                "total": self.valves.TASK_BUDGET_TOKENS
            }
        if self.valves.FALLBACK_MODEL.strip():
            options_kwargs["fallback_model"] = self.valves.FALLBACK_MODEL.strip()

        # Extend Claude Code's default agent-loop system prompt with whatever
        # the Workspace Model configured. `append` keeps the agentic prompt
        # intact while adding domain persona/rules on top.
        append_parts: List[str] = []
        # The gateway contract goes first so the operator's Workspace-Model
        # prompt is the LATER text: on a persona/style conflict the operator
        # wins, which is the precedence we want. (Presence, not position, is
        # what protects a repo-rooted session — position only decides ties.)
        if self.valves.GATEWAY_CONTRACT_PATH:
            # The WORKDIR_ROOT exemption assumes a scratch session loads
            # <WORKDIR_ROOT>/CLAUDE.md by itself — true only while
            # SETTING_SOURCES lets it. That valve defaults to "" (load
            # nothing), so without this check a valve reset would leave every
            # scratch AND keyless session contractless while repo-rooted ones
            # stayed covered: the exact inversion of the bug this fixes.
            loads_from_cwd = "project" in _parse_setting_sources(
                self.valves.SETTING_SOURCES
            )
            contract = _gateway_contract(
                str(cwd),
                self.valves.WORKDIR_ROOT if loads_from_cwd else "",
                self.valves.GATEWAY_CONTRACT_PATH,
            )
            if contract:
                append_parts.append(contract)
        system_prompt = _extract_system_prompt(body)
        if system_prompt:
            append_parts.append(system_prompt)
        if not chat_id:
            # Keyless callers are mobile/voice surfaces (Conduit): small
            # screens, often TTS. Nudge hard toward brevity.
            append_parts.append(
                "Surface note: this reply may render on a small mobile "
                "screen. Answer as concisely as correctness allows — lead "
                "with the answer, no headers unless essential, no trailing "
                "recap."
            )
        if append_parts:
            options_kwargs["system_prompt"] = {
                "type": "preset",
                "preset": "claude_code",
                "append": "\n\n".join(append_parts),
            }

        agent_env = _agent_env(chat_id)
        if agent_env:
            options_kwargs["env"] = {**options_kwargs.get("env", {}), **agent_env}

        options = ClaudeAgentOptions(**options_kwargs)

        async def emit_status(description: str, done: bool = False) -> None:
            if __event_emitter__ is None:
                return
            await __event_emitter__(
                {"type": "status", "data": {"description": description, "done": done}}
            )

        await emit_status("Starting Claude Code…")
        # Claude often saves generated files to /tmp from habit (absolute paths
        # in matplotlib/PIL examples), even though cwd is the chat workdir.
        # Scan both so we don't miss the image.
        scan_dirs = [workdir, Path("/tmp")]
        artifact_snapshot = _snapshot_artifacts(scan_dirs)

        state = _TurnState()
        heartbeat_task: Optional[asyncio.Task] = None
        inline = self.valves.INLINE_TOOL_DETAILS

        # While a tool runs, restate elapsed time every 2s so a 30s Bash call
        # reads as progress rather than a hang.
        async def _heartbeat() -> None:
            try:
                while state.active_tools:
                    await asyncio.sleep(2)
                    if not state.active_tools:
                        return
                    label, elapsed = _heartbeat_label(state.active_tools, time.monotonic())
                    log.debug("heartbeat tick: %s · %ss", label, elapsed)
                    await emit_status(f"⏳ {label} · running {elapsed}s…")
            except asyncio.CancelledError:
                pass

        def _ensure_heartbeat() -> None:
            nonlocal heartbeat_task
            if heartbeat_task is None or heartbeat_task.done():
                heartbeat_task = asyncio.create_task(_heartbeat())

        try:
            async with ClaudeSDKClient(options=options) as client:
                await client.query(prompt)
                async for message in client.receive_response():
                    if isinstance(message, SystemMessage):
                        if message.subtype == "init":
                            session_id = message.data.get("session_id")
                            if session_id:
                                state.turn_session_id = session_id
                                if chat_id:
                                    _chat_sessions[chat_id] = session_id
                                    _save_session_meta(
                                        self.valves.WORKDIR_ROOT,
                                        chat_id,
                                        {"session_id": session_id, "cwd": str(cwd)},
                                    )
                            await emit_status(_session_status(
                                bool(resume_id),
                                _strip_latest_user(body.get("messages") or []),
                            ))
                        elif message.subtype == "compact_boundary":
                            # Auto-compaction summarized earlier history — the
                            # context number will drop; say why.
                            await emit_status("Session: context compacted")
                        continue

                    if isinstance(message, StreamEvent):
                        chunks, status = _on_stream_event(message.event or {}, state, inline)
                        if status:
                            await emit_status(status)
                        for chunk in chunks:
                            yield chunk
                        continue

                    if isinstance(message, AssistantMessage):
                        state.note_assistant(
                            message.parent_tool_use_id is None,
                            message.usage,
                            sum(isinstance(b, ToolUseBlock) for b in message.content),
                        )
                        # Text and thinking already streamed via StreamEvent;
                        # tool input is only complete here.
                        for block in message.content:
                            if not isinstance(block, ToolUseBlock):
                                continue
                            chunks, status = _on_tool_use(
                                block.name, block.input, block.id, state, inline,
                                time.monotonic(),
                            )
                            if status:
                                await emit_status(status)
                            _ensure_heartbeat()
                            for chunk in chunks:
                                yield chunk
                        continue

                    if isinstance(message, UserMessage):
                        if not isinstance(message.content, list):
                            continue
                        for block in message.content:
                            if not isinstance(block, ToolResultBlock):
                                continue
                            chunks, status = _on_tool_result(
                                block.tool_use_id, block.is_error, block.content,
                                state, inline,
                            )
                            if status:
                                await emit_status(status)
                            for chunk in chunks:
                                yield chunk
                        continue

                    if isinstance(message, ResultMessage):
                        ctx = ""
                        try:
                            cu = await asyncio.wait_for(
                                client.get_context_usage(), timeout=5
                            )
                            ctx = _context_from_usage(cu)
                        except Exception:
                            log.debug("get_context_usage failed", exc_info=True)
                        if not ctx:
                            ctx = _context_status(
                                state.last_usage, self.valves.CONTEXT_WINDOW_TOKENS
                            )
                        await emit_status(
                            _done_line(message.duration_ms, state.tool_count, ctx),
                            done=True,
                        )
                        if state.last_usage:
                            await self._record_usage(
                                _owui_usage(state.last_usage),
                                __event_emitter__,
                                __metadata__,
                            )
                        for chunk in _inline_new_artifacts(
                            scan_dirs,
                            artifact_snapshot,
                            (__user__ or {}).get("id"),
                        ):
                            yield chunk
                        if message.subtype != "success":
                            yield f"\n\n_Agent stopped: {message.subtype}_\n"
                        # No cost footer: subscription billing makes it noise,
                        # and TTS reads it aloud in call mode.
                        if turn_info is not None and state.turn_session_id:
                            turn_info["session_id"] = state.turn_session_id
                            turn_info["workdir"] = str(workdir)
                            turn_info["cwd"] = str(cwd)
                        return

        except CLIJSONDecodeError:
            log.exception("Claude Agent SDK pipe exceeded the stream-json buffer")
            await emit_status("Error: response exceeded read buffer", done=True)
            yield (
                "\n\n**Response too large to read back.** A single message from "
                "the Claude Code CLI exceeded the "
                f"{self.valves.MAX_BUFFER_MB} MiB `MAX_BUFFER_MB` limit — "
                "usually a very large file or image read into the transcript. "
                "Raise `MAX_BUFFER_MB` in the pipe's valves, or work with a "
                "smaller file.\n"
            )
        except Exception as exc:
            if resume_id and state.turn_session_id is None:
                # Resume died before the session came up. Drop the stale id
                # and rerun this turn cold — _render_transcript replays the
                # history, and the new session id gets persisted on init.
                log.warning(
                    "resume of %s failed (%s: %s); retrying cold",
                    resume_id, type(exc).__name__, exc,
                )
                if chat_id:
                    _chat_sessions.pop(chat_id, None)
                    _save_session_meta(
                        self.valves.WORKDIR_ROOT, chat_id, {"cwd": str(cwd)}
                    )
                await emit_status("Session expired — replaying history…")
                async for chunk in self._pipe_stream(
                    body, __chat_id__, __event_emitter__, __files__,
                    __user__, __metadata__,
                    turn_info=turn_info, _no_resume=True,
                ):
                    yield chunk
                return
            log.exception("Claude Agent SDK pipe failed")
            await emit_status(f"Error: {exc}", done=True)
            yield f"\n\n**Claude Code error:** `{type(exc).__name__}: {exc}`\n"
        finally:
            state.active_tools.clear()
            if heartbeat_task is not None and not heartbeat_task.done():
                heartbeat_task.cancel()
                try:
                    await heartbeat_task
                except asyncio.CancelledError:
                    pass
