    class Valves(BaseModel):
        ANTHROPIC_API_KEY: str = Field(
            default="",
            description="Anthropic API key (pay-per-token). Leave empty to use the subscription OAuth token or inherit from the backend env.",
        )
        CLAUDE_CODE_OAUTH_TOKEN: str = Field(
            default="",
            description=(
                "Long-lived Claude Pro/Max/Team OAuth token generated by "
                "`claude setup-token` on a machine with a browser. When set, "
                "bills against your subscription (not the API). Takes priority "
                "over ANTHROPIC_API_KEY — the key gets unset so it can't "
                "override. Anthropic's terms: use your own subscription only, "
                "don't re-offer subscription auth to end users."
            ),
        )
        MODEL: str = Field(
            default="claude-haiku-4-5",
            description="Claude model ID (e.g. claude-haiku-4-5, claude-sonnet-4-6, claude-opus-4-7).",
        )
        MODELS: str = Field(
            default="",
            description=(
                "Comma-separated EXTRA Claude model IDs to expose as separate "
                "picker entries (e.g. claude-haiku-4-5,claude-opus-4-8). Each "
                "gets its own model named by ID; the base entry still uses MODEL."
            ),
        )
        INLINE_TOOL_DETAILS: bool = Field(
            default=True,
            description=(
                "Render tool inputs/thinking as inline <details> blocks in the "
                "message text. The web UI shows these as collapsibles, but some "
                "mobile clients (e.g. Conduit) render the raw tags as text - "
                "set False there; tool activity still appears via status events."
            ),
        )
        PERMISSION_MODE: str = Field(
            default="bypassPermissions",
            description='Permission mode: "default", "acceptEdits", "bypassPermissions", "plan", or "dontAsk".',
        )
        ALLOWED_TOOLS: str = Field(
            default="Read,Write,Edit,Bash,Glob,Grep,WebSearch,WebFetch",
            description="Comma-separated tools auto-approved without prompting.",
        )
        WORKDIR_ROOT: str = Field(
            default=_DEFAULT_WORKDIR_ROOT,
            description=(
                "Root directory for per-chat workspaces (one subdir per chat) "
                "and the pipe's session metadata. Must be writable by the "
                "Open WebUI process; make it persistent so sessions survive "
                "restarts. Blank falls back to the default."
            ),
        )
        CLAUDE_CONFIG_DIR: str = Field(
            default="",
            description=(
                "Directory the Claude Code CLI keeps its own state in "
                "(session transcripts, settings) — the CLAUDE_CONFIG_DIR it "
                "is started with. Empty inherits the process default, "
                "$HOME/.claude. In a container, set a persistent path (e.g. "
                "<WORKDIR_ROOT>/claude-config) or every session dies with "
                "the container; note SETTING_SOURCES=user then reads "
                "CLAUDE.md and settings.json from here, not from ~/.claude."
            ),
        )
        GATEWAY_CONTRACT_PATH: str = Field(
            default="",
            description=(
                "Path to a rules file (e.g. ~/gateway/AGENTS.md) appended to "
                "the system prompt when a chat is rooted "
                "outside WORKDIR_ROOT (a #repo: session), where the agent would "
                "otherwise load only that repo's CLAUDE.md and never see the "
                "gateway's Hard Rules. Empty disables the append."
            ),
        )
        ASK_USER: bool = Field(
            default=True,
            description=(
                "Register the ask_user tool: the agent can pause mid-turn and "
                "show a multiple-choice form (Open WebUI's request:user_input "
                "event). Clients without a socket session (mobile apps, API "
                "callers) get the questions as markdown in the reply and "
                "answer in the next message instead."
            ),
        )
        SESSION_SEARCH: bool = Field(
            default=True,
            description=(
                "Register search_chats / read_chat: the agent can look up the "
                "calling user's earlier chats in this Open WebUI (read-only "
                "sqlite over the chat table, scoped to that user). Only "
                "sqlite deployments; leave on elsewhere, the tools then report "
                "themselves unavailable."
            ),
        )
        CHAT_DB_PATH: str = Field(
            default="",
            description=(
                "Path to Open WebUI's webui.db for SESSION_SEARCH. Empty "
                "resolves DATA_DIR/webui.db from the running Open WebUI."
            ),
        )
        MAX_TURNS: int = Field(
            default=30,
            description="Maximum agent turns per user message. 0 disables the cap.",
        )
        CONTEXT_WINDOW_TOKENS: int = Field(
            default=200_000,
            description=(
                "FALLBACK context window (tokens) for the post-turn "
                "'Done · context X/Y (N%)' status line, used only when the "
                "SDK's live context query fails (which otherwise supplies the "
                "real per-model window). 0 disables the fallback suffix."
            ),
        )
        EFFORT: str = Field(
            default="",
            description=(
                "Default effort level for agent turns: low|medium|high|xhigh|"
                "max. Empty = SDK default (high). A message starting with "
                "'/effort <level>' overrides it for that turn."
            ),
        )
        TASK_BUDGET_TOKENS: int = Field(
            default=0,
            description=(
                "Per-turn token budget the model is made aware of and paces "
                "itself against (output_config.task_budget). API minimum is "
                "20000 — smaller nonzero values are ignored. 0 disables."
            ),
        )
        FALLBACK_MODEL: str = Field(
            default="",
            description=(
                "Model to retry with if the primary model fails or is "
                "unavailable (SDK fallback_model). Empty disables."
            ),
        )
        MAX_BUFFER_MB: int = Field(
            default=32,
            description=(
                "Maximum size (MiB) of a single stream-json message read back "
                "from the Claude Code CLI. The SDK's own default is 1 MiB, "
                "which a Read of any attachment over ~780 KiB blows past once "
                "base64 expansion (~1.34x) and the JSON envelope are counted — "
                "killing the message reader mid-response. 32 MiB clears the "
                "10 MiB image-attachment cap with room to spare and matches "
                "the Anthropic API's own 32 MB request-body ceiling, so the "
                "framer stops rejecting payloads the API would have accepted. "
                "0 falls back to the SDK default."
            ),
        )
        SCAN_TMP_ARTIFACTS: bool = Field(
            default=False,
            description=(
                "Also scan /tmp for files the agent created during the turn "
                "and attach them to the reply (the agent often writes there "
                "from habit). /tmp is shared by every user of the host, so a "
                "file another chat wrote in the same window would be "
                "attached too — enable on single-user hosts only."
            ),
        )
        SETTING_SOURCES: str = Field(
            default="",
            description=(
                "Comma-separated Claude Code setting sources to load: any of "
                '"user", "project", "local". Empty (default) loads NONE — each '
                "chat runs from a clean baseline and does NOT inherit the "
                "backend user's ~/.claude/ or the workdir's .claude/ config. "
                'Add "user" to load ~/.claude/CLAUDE.md and ~/.claude/'
                "settings.json (persistent context for single-user "
                "setups). WARNING: settings.json can define hooks that execute "
                "code and permission grants — only enable on instances you "
                "trust and control. Avoid on multi-user/public deployments."
            ),
        )
        REPO_MAP: str = Field(
            default="",
            description=(
                "Comma-separated name=path allowlist of repos a chat may run "
                "in, e.g. app=/srv/app,notes=/home/me/notes. Start a chat's "
                "FIRST message with #repo:<name> to set its cwd to that path "
                "for the whole chat (loads the repo's CLAUDE.md via the "
                "project setting source). Unknown names error in-chat. Empty "
                "disables the feature. Grants nothing new — bypassPermissions "
                "already reaches these paths; this only controls cwd."
            ),
        )

    def __init__(self) -> None:
        self.valves = self.Valves()

    def pipes(self) -> List[Dict[str, str]]:
        entries = [{"id": "claude-code", "name": "Claude Code"}]
        for m in [m.strip() for m in self.valves.MODELS.split(",") if m.strip()]:
            entries.append({"id": f"claude-code-{m}", "name": f"Claude Code ({m})"})
        return entries

    def _resolve_model(self, body: Optional[Dict[str, Any]]) -> str:
        return _model_from_requested(
            str((body or {}).get("model") or ""), self.valves.MODEL
        )

    async def pipe(
        self,
        body: Dict[str, Any],
        __chat_id__: Optional[str] = None,
        __event_emitter__: Optional[Callable] = None,
        __files__: Optional[List[Dict[str, Any]]] = None,
        __user__: Optional[Dict[str, Any]] = None,
        __metadata__: Optional[Dict[str, Any]] = None,
        __event_call__: Optional[Callable] = None,
    ) -> AsyncGenerator[str, None]:
        """Public entrypoint. Scrubs secrets from everything leaving the pipe.

        Kept as a thin wrapper around `_pipe_stream` so the redaction can't be
        bypassed by a future `yield` added inside the agent loop: both the
        response stream and the status/event channel pass through here.
        OpenWebUI injects the dunder arguments by signature inspection, so
        this wrapper must keep the original parameter list verbatim.
        """
        redactor = _StreamRedactor()
        workdir_root = _workdir_root(self.valves.WORKDIR_ROOT)
        event_hits: List[str] = []
        emitter = _redacting_emitter(__event_emitter__, event_hits)

        turn_info: Dict[str, Any] = {}
        emitted_parts: List[str] = []

        inflight: Optional[_InflightTurn] = None
        if __chat_id__:
            inflight, superseded = await _claim_chat(__chat_id__)
            if superseded and __event_emitter__ is not None:
                await __event_emitter__({
                    "type": "status",
                    "data": {
                        "description": "Stopped the turn still running in this chat",
                        "done": False,
                    },
                })

        # The `finally` only releases the in-flight claim — it must never
        # yield: flushing from there would mean yielding during GeneratorExit
        # if the client disconnects mid-stream, which raises RuntimeError.
        # Dropping a held tail on an aborted stream is the safe direction — it
        # withholds text rather than emitting it.
        try:
            async for chunk in self._pipe_stream(
                body, __chat_id__, emitter, __files__, __user__, __metadata__,
                turn_info=turn_info, event_call=__event_call__, inflight=inflight,
            ):
                safe = redactor.feed(chunk)
                if safe:
                    if not __chat_id__:
                        emitted_parts.append(safe)
                    yield safe
        finally:
            if inflight is not None and __chat_id__:
                _release_chat(__chat_id__, inflight)

        tail = redactor.flush()
        if tail:
            if not __chat_id__:
                emitted_parts.append(tail)
            yield tail

        # Keyless turn finished cleanly → register its post-turn fingerprint
        # so the NEXT call (whose prefix is this history + this reply) resumes
        # warm. If redaction fired, the client-stored text differs from what
        # the agent produced — the next lookup misses and replays once; safe.
        if not __chat_id__ and turn_info.get("session_id"):
            store = _load_fp_store(workdir_root)
            fp = _history_fingerprint(
                (body.get("messages") or [])
                + [{"role": "assistant", "content": "".join(emitted_parts)}]
            )
            # An all-empty normalization must never claim the shared
            # empty-prefix hash that every brand-new keyless chat's cold
            # lookup collides on.
            if fp != _EMPTY_FP:
                store[fp] = {
                    "session_id": turn_info["session_id"],
                    "workdir": turn_info["workdir"],
                    "cwd": turn_info.get("cwd") or turn_info["workdir"],
                    "ts": time.time(),
                }
                _save_fp_store(workdir_root, store)

        hits = redactor.hits + event_hits
        if hits:
            # Log the kinds, never the values. A hit means something read a
            # credential into the response path — worth a rotation decision
            # even though the value never reached the chat DB.
            log.warning(
                "pipe output redaction fired: %s",
                ", ".join(f"{k}×{hits.count(k)}" for k in sorted(set(hits))),
            )

    async def _record_usage(
        self,
        usage_payload: Dict[str, int],
        __event_emitter__: Optional[Callable],
        __metadata__: Optional[Dict[str, Any]],
    ) -> None:
        """Publish the turn's usage twice: a chat:completion event for live
        listeners (never persisted), and a direct write to the saved message —
        the socket emitter's save_to_chat branch drops chat:completion, and the
        message's ⓘ popover renders only from the saved `usage`. The upsert
        merges keys, so the middleware's later {'done', 'output'} upsert keeps
        it; isawaitable covers OWUI versions where the upsert is sync. Both
        paths are best-effort: a failure here must not break the turn."""
        if __event_emitter__ is not None:
            try:
                await __event_emitter__(
                    {"type": "chat:completion", "data": {"usage": usage_payload}}
                )
            except Exception:
                log.debug("usage emit failed", exc_info=True)
        try:
            chat_id_meta = (__metadata__ or {}).get("chat_id")
            msg_id_meta = (__metadata__ or {}).get("message_id")
            if chat_id_meta and msg_id_meta:
                from open_webui.models.chats import Chats

                res = Chats.upsert_message_to_chat_by_id_and_message_id(
                    chat_id_meta, msg_id_meta, {"usage": usage_payload}, touch=False
                )
                if inspect.isawaitable(res):
                    await res
        except Exception:
            log.debug("usage DB write failed", exc_info=True)

    async def _pipe_stream(
        self,
        body: Dict[str, Any],
        __chat_id__: Optional[str] = None,
        __event_emitter__: Optional[Callable] = None,
        __files__: Optional[List[Dict[str, Any]]] = None,
        __user__: Optional[Dict[str, Any]] = None,
        __metadata__: Optional[Dict[str, Any]] = None,
        *,
        turn_info: Optional[Dict[str, Any]] = None,
        event_call: Optional[Callable] = None,
        _no_resume: bool = False,
        inflight: Optional[_InflightTurn] = None,
    ) -> AsyncGenerator[str, None]:
        # Auth selection:
        #   1. If CLAUDE_CODE_OAUTH_TOKEN valve is set → use subscription.
        #      Remove any ANTHROPIC_API_KEY from env because per Claude Code's
        #      precedence order, the API key outranks the OAuth token (docs:
        #      code.claude.com/docs/en/authentication#authentication-precedence)
        #      and would otherwise silently win.
        #   2. Else if ANTHROPIC_API_KEY valve is set → use API.
        #   3. Else → whatever the backend environment already provides.
        if self.valves.CLAUDE_CODE_OAUTH_TOKEN:
            os.environ["CLAUDE_CODE_OAUTH_TOKEN"] = self.valves.CLAUDE_CODE_OAUTH_TOKEN
            os.environ.pop("ANTHROPIC_API_KEY", None)
            os.environ.pop("ANTHROPIC_AUTH_TOKEN", None)
        elif self.valves.ANTHROPIC_API_KEY:
            os.environ["ANTHROPIC_API_KEY"] = self.valves.ANTHROPIC_API_KEY
        # claude CLI refuses --dangerously-skip-permissions under root unless
        # told it's inside a sandbox. OpenWebUI's backend runs as UID 0.
        os.environ.setdefault("IS_SANDBOX", "1")
        # HUB_CHAT_ID reaches the agent exactly one way: `_agent_env` putting it
        # in this client's `ClaudeAgentOptions.env`. `_agent_env` omitting the
        # key means "inherit", not "guaranteed unset" — so for a caller with no chat
        # id, an ambient HUB_CHAT_ID in Open WebUI's own environment would flow
        # straight through to the agent, and any tooling that delivers results
        # by chat id would post into someone else's conversation. Clearing it
        # here makes the per-client value the only path there is.
        os.environ.pop("HUB_CHAT_ID", None)

        workdir_root = _workdir_root(self.valves.WORKDIR_ROOT)
        prompt = _extract_latest_user_prompt(body)
        if not prompt:
            yield "_No user message to send to Claude Code._"
            return

        # `/agent` and `/fast` prefixes are accepted and stripped for callers
        # that still type them; there is only the full agent loop.
        prompt = _strip_mode_prefix(prompt)
        repo_name, prompt = _extract_repo_prefix(prompt)
        effort_override, prompt = _extract_effort_prefix(prompt)

        # Keyless callers (no __chat_id__ — generic OpenAI-API clients such
        # as Conduit or voice integrations don't send OWUI's proprietary
        # top-level `chat_id` field) get session identity from a fingerprint
        # of the conversation prefix rather than from chat_id — see the
        # block below. A cold start (first turn, or a fingerprint miss: new
        # chat, edited message, pruned entry) replays the full
        # body["messages"] history as a transcript once, then resumes warm.
        # Keyed callers (native UI) keep session resume; on a cold start
        # (map entry lost, e.g. after an OWUI restart) they too replay
        # history once, then resume warm from the new session.
        chat_id = __chat_id__ or None
        # Keyless callers (Conduit, generic OpenAI-API clients) get session
        # identity by fingerprinting the conversation prefix. Hit → resume
        # that session in its own workdir (warm, tool results intact).
        # Miss (new chat, edited message) → fresh uuid workdir, replay once,
        # register after the turn. This also retires the old shared
        # "default" workdir where all keyless chats collided.
        fp_entry: Optional[Dict[str, Any]] = None
        if chat_id:
            workdir = Path(workdir_root) / chat_id
        else:
            fp_entry = _load_fp_store(workdir_root).get(
                _history_fingerprint(
                    _strip_latest_user(body.get("messages") or [])
                )
            )
            if fp_entry and not fp_entry.get("workdir"):
                # Malformed/partial entry — treat as a miss rather than
                # trusting a workdir (or session_id) that isn't there.
                fp_entry = None
            if fp_entry:
                workdir = Path(fp_entry["workdir"])
            else:
                workdir = (
                    Path(workdir_root)
                    / f"anon-{uuid.uuid4().hex[:12]}"
                )
        try:
            workdir.mkdir(parents=True, exist_ok=True)
        except OSError as exc:
            yield (
                f"_Cannot create the chat workspace `{workdir}` ({exc}). "
                "Point the `WORKDIR_ROOT` valve at a directory the Open WebUI "
                "process can write._"
            )
            return

        # cwd: persisted repo choice wins; else an explicit #repo: prefix on
        # a fresh session; else the scratch workdir. Metadata lives under
        # WORKDIR_ROOT regardless — never inside a repo.
        repo_map = _parse_repo_map(self.valves.REPO_MAP)
        cwd = Path(
            (
                _load_session_meta(workdir_root, chat_id).get("cwd")
                if chat_id
                else (fp_entry or {}).get("cwd")
            )
            or workdir
        )
        if repo_name is not None:
            if repo_name not in repo_map:
                allowed = ", ".join(sorted(repo_map)) or "(none configured)"
                yield (
                    f"_Unknown repo `{repo_name}`. Allowed: {allowed}._"
                )
                return
            target = Path(repo_map[repo_name])
            if not target.is_dir():
                yield f"_Repo path for `{repo_name}` does not exist on the host._"
                return
            if chat_id:
                has_session = bool(
                    _chat_sessions.get(chat_id)
                    or _load_session_meta(workdir_root, chat_id).get(
                        "session_id"
                    )
                )
            else:
                has_session = bool(fp_entry and fp_entry.get("session_id"))
            if has_session and cwd != target:
                # A live session already exists for this chat; Claude Code
                # sessions are per-directory, so switching mid-chat can't
                # resume. Tell the user instead of silently degrading.
                yield (
                    "_This chat already runs in another directory; `#repo:` "
                    "only takes effect on a chat's first message. Start a "
                    "new chat._"
                )
                return
            cwd = target

        allowed_tools = [
            t.strip() for t in self.valves.ALLOWED_TOOLS.split(",") if t.strip()
        ]
        # In-process map is a cache; the meta file survives OWUI restarts,
        # pipe redeploys, and valve edits.
        resume_id: Optional[str] = None
        if not _no_resume:
            if chat_id:
                resume_id = _chat_sessions.get(chat_id) or _load_session_meta(
                    workdir_root, chat_id
                ).get("session_id")
            elif fp_entry:
                resume_id = fp_entry.get("session_id")

        # Image attachments on the latest user message: OWUI delivers them as
        # image_url content parts, which the text-only prompt extraction
        # drops. Write them to files under the workdir and reference the
        # paths in the prompt so the agent can Read them.
        attachment_notes = _save_image_attachments(body, workdir)
        if attachment_notes:
            prompt = prompt + "\n\n" + "\n".join(attachment_notes)

        if resume_id is None:
            prompt = _render_transcript(body, prompt)

        # Knowledge base attached via Workspace Model → expose as an MCP tool
        # Claude can call agentically. OpenWebUI's middleware already added one
        # entry per attached KB to files/__files__.
        kb_server, kb_tool_names = _build_kb_mcp_server(
            _knowledge_collections(__metadata__, __files__),
            knowledge_row_ids=_knowledge_row_ids(__metadata__),
            user_dict=__user__,
            event_emitter=__event_emitter__,
        )
        allowed_tools = allowed_tools + kb_tool_names
        mcp_servers: Dict[str, Any] = {}
        if kb_server is not None:
            mcp_servers["knowledge"] = kb_server
        if self.valves.ASK_USER:
            ask_server, ask_tool_names = _build_ask_user_mcp_server(event_call)
            mcp_servers["ask-user"] = ask_server
            allowed_tools = allowed_tools + ask_tool_names
        chats_server = None
        if self.valves.SESSION_SEARCH:
            chats_server, chats_tool_names = _build_chats_mcp_server(
                (__user__ or {}).get("id"), chat_id,
                _owui_db_path(self.valves.CHAT_DB_PATH.strip()),
            )
            if chats_server is not None:
                mcp_servers["chats"] = chats_server
                allowed_tools = allowed_tools + chats_tool_names

        options_kwargs: Dict[str, Any] = {
            "cwd": str(cwd),
            "model": self._resolve_model(body),
            "permission_mode": self.valves.PERMISSION_MODE,
            "allowed_tools": allowed_tools,
            # Which filesystem settings to load (user ~/.claude/, project .claude/,
            # local). Default empty = clean baseline, no inheritance of the backend
            # user's config. Opt in via the SETTING_SOURCES valve (e.g. "user" to
            # load ~/.claude/CLAUDE.md). See the valve's security warning.
            "setting_sources": _parse_setting_sources(self.valves.SETTING_SOURCES),
            # Stream token-level deltas so long answers type out instead of
            # appearing as one chunk when the block finishes.
            "include_partial_messages": True,
        }
        if resume_id:
            options_kwargs["resume"] = resume_id
        if self.valves.MAX_TURNS:
            options_kwargs["max_turns"] = self.valves.MAX_TURNS
        if self.valves.MAX_BUFFER_MB:
            options_kwargs["max_buffer_size"] = (
                self.valves.MAX_BUFFER_MB * 1024 * 1024
            )
        if mcp_servers:
            options_kwargs["mcp_servers"] = mcp_servers
        effort = effort_override or self.valves.EFFORT.strip().lower() or None
        if effort in _EFFORT_LEVELS:
            options_kwargs["effort"] = effort
        if self.valves.TASK_BUDGET_TOKENS >= 20_000:
            options_kwargs["task_budget"] = {
                "total": self.valves.TASK_BUDGET_TOKENS
            }
        if self.valves.FALLBACK_MODEL.strip():
            options_kwargs["fallback_model"] = self.valves.FALLBACK_MODEL.strip()

        # Extend Claude Code's default agent-loop system prompt with whatever
        # the Workspace Model configured. `append` keeps the agentic prompt
        # intact while adding domain persona/rules on top.
        append_parts: List[str] = []
        # The gateway contract goes first so the operator's Workspace-Model
        # prompt is the LATER text: on a persona/style conflict the operator
        # wins, which is the precedence we want. (Presence, not position, is
        # what protects a repo-rooted session — position only decides ties.)
        if self.valves.GATEWAY_CONTRACT_PATH:
            # The WORKDIR_ROOT exemption assumes a scratch session loads
            # <WORKDIR_ROOT>/CLAUDE.md by itself — true only while
            # SETTING_SOURCES lets it. That valve defaults to "" (load
            # nothing), so without this check a valve reset would leave every
            # scratch AND keyless session contractless while repo-rooted ones
            # stayed covered: the exact inversion of the bug this fixes.
            loads_from_cwd = "project" in _parse_setting_sources(
                self.valves.SETTING_SOURCES
            )
            contract = _gateway_contract(
                str(cwd),
                workdir_root if loads_from_cwd else "",
                self.valves.GATEWAY_CONTRACT_PATH,
            )
            if contract:
                append_parts.append(contract)
        system_prompt = _extract_system_prompt(body)
        if system_prompt:
            append_parts.append(system_prompt)
        if self.valves.ASK_USER:
            append_parts.append(_ASK_USER_PROMPT)
        if chats_server is not None:
            append_parts.append(_CHATS_PROMPT)
        if not chat_id:
            # Keyless callers are mobile/voice surfaces (Conduit): small
            # screens, often TTS. Nudge hard toward brevity.
            append_parts.append(
                "Surface note: this reply may render on a small mobile "
                "screen. Answer as concisely as correctness allows — lead "
                "with the answer, no headers unless essential, no trailing "
                "recap."
            )
        if append_parts:
            options_kwargs["system_prompt"] = {
                "type": "preset",
                "preset": "claude_code",
                "append": "\n\n".join(append_parts),
            }

        agent_env = _agent_env(chat_id)
        if self.valves.CLAUDE_CONFIG_DIR.strip():
            agent_env["CLAUDE_CONFIG_DIR"] = str(
                Path(self.valves.CLAUDE_CONFIG_DIR.strip()).expanduser()
            )
        if agent_env:
            options_kwargs["env"] = {**options_kwargs.get("env", {}), **agent_env}

        options = ClaudeAgentOptions(**options_kwargs)

        async def emit_status(description: str, done: bool = False) -> None:
            if __event_emitter__ is None:
                return
            await __event_emitter__(
                {"type": "status", "data": {"description": description, "done": done}}
            )

        await emit_status("Starting Claude Code…")
        # Claude often saves generated files to /tmp from habit (absolute paths
        # in matplotlib/PIL examples), even though cwd is the chat workdir.
        # /tmp is shared by every user of the host, so scanning it is opt-in.
        scan_dirs = [workdir]
        if self.valves.SCAN_TMP_ARTIFACTS:
            scan_dirs.append(Path("/tmp"))
        artifact_snapshot = _snapshot_artifacts(scan_dirs)

        state = _TurnState()
        heartbeat_task: Optional[asyncio.Task] = None
        inline = self.valves.INLINE_TOOL_DETAILS

        # While a tool runs, restate elapsed time every 2s so a 30s Bash call
        # reads as progress rather than a hang.
        async def _heartbeat() -> None:
            try:
                while state.active_tools:
                    await asyncio.sleep(2)
                    if not state.active_tools:
                        return
                    label, elapsed = _heartbeat_label(state.active_tools, time.monotonic())
                    log.debug("heartbeat tick: %s · %ss", label, elapsed)
                    await emit_status(f"⏳ {label} · running {elapsed}s…")
            except asyncio.CancelledError:
                pass

        def _ensure_heartbeat() -> None:
            nonlocal heartbeat_task
            if heartbeat_task is None or heartbeat_task.done():
                heartbeat_task = asyncio.create_task(_heartbeat())

        try:
            async with ClaudeSDKClient(options=options) as client:
                if inflight is not None:
                    inflight.interrupt = client.interrupt
                    if inflight.stopped_previous:
                        prompt = _with_overlap_note(prompt)
                await client.query(prompt)
                async for message in client.receive_response():
                    if isinstance(message, SystemMessage):
                        if message.subtype == "init":
                            session_id = message.data.get("session_id")
                            if session_id:
                                state.turn_session_id = session_id
                                if chat_id:
                                    _chat_sessions[chat_id] = session_id
                                    _save_session_meta(
                                        workdir_root,
                                        chat_id,
                                        {"session_id": session_id, "cwd": str(cwd)},
                                    )
                            await emit_status(_session_status(
                                bool(resume_id),
                                _strip_latest_user(body.get("messages") or []),
                            ))
                        elif message.subtype == "compact_boundary":
                            # Auto-compaction summarized earlier history — the
                            # context number will drop; say why.
                            await emit_status("Session: context compacted")
                        continue

                    if isinstance(message, StreamEvent):
                        # A subagent's own text is its report back to the main
                        # thread, not the reply; it would stream as a duplicate.
                        if message.parent_tool_use_id is not None:
                            continue
                        chunks, status = _on_stream_event(message.event or {}, state, inline)
                        if status:
                            await emit_status(status)
                        for chunk in chunks:
                            yield chunk
                        continue

                    if isinstance(message, AssistantMessage):
                        state.note_assistant(
                            message.parent_tool_use_id is None,
                            message.usage,
                            sum(isinstance(b, ToolUseBlock) for b in message.content),
                        )
                        # Text and thinking already streamed via StreamEvent;
                        # tool input is only complete here.
                        for block in message.content:
                            if not isinstance(block, ToolUseBlock):
                                continue
                            chunks, status = _on_tool_use(
                                block.name, block.input, block.id, state, inline,
                                time.monotonic(), message.parent_tool_use_id,
                            )
                            if status:
                                await emit_status(status)
                            _ensure_heartbeat()
                            for chunk in chunks:
                                yield chunk
                        continue

                    if isinstance(message, UserMessage):
                        if not isinstance(message.content, list):
                            continue
                        for block in message.content:
                            if not isinstance(block, ToolResultBlock):
                                continue
                            chunks, status = _on_tool_result(
                                block.tool_use_id, block.is_error, block.content,
                                state, inline, time.monotonic(),
                            )
                            if status:
                                await emit_status(status)
                            for chunk in chunks:
                                yield chunk
                        continue

                    if isinstance(message, ResultMessage):
                        ctx = ""
                        try:
                            cu = await asyncio.wait_for(
                                client.get_context_usage(), timeout=5
                            )
                            ctx = _context_from_usage(cu)
                        except Exception:
                            log.debug("get_context_usage failed", exc_info=True)
                        if not ctx:
                            ctx = _context_status(
                                state.last_usage, self.valves.CONTEXT_WINDOW_TOKENS
                            )
                        await emit_status(
                            _done_line(
                                message.duration_ms, state.tool_count, ctx,
                                state.agent_count,
                            ),
                            done=True,
                        )
                        if state.last_usage:
                            await self._record_usage(
                                _owui_usage(state.last_usage),
                                __event_emitter__,
                                __metadata__,
                            )
                        for chunk in _inline_new_artifacts(
                            scan_dirs,
                            artifact_snapshot,
                            (__user__ or {}).get("id"),
                        ):
                            yield chunk
                        if inflight is not None and inflight.superseded:
                            yield "\n\n_Stopped: a newer message arrived in this chat._\n"
                        elif message.subtype != "success":
                            yield f"\n\n_Agent stopped: {message.subtype}_\n"
                        # No cost footer: subscription billing makes it noise,
                        # and TTS reads it aloud in call mode.
                        if turn_info is not None and state.turn_session_id:
                            turn_info["session_id"] = state.turn_session_id
                            turn_info["workdir"] = str(workdir)
                            turn_info["cwd"] = str(cwd)
                        return

        except CLIJSONDecodeError:
            log.exception("Claude Agent SDK pipe exceeded the stream-json buffer")
            await emit_status("Error: response exceeded read buffer", done=True)
            yield (
                "\n\n**Response too large to read back.** A single message from "
                "the Claude Code CLI exceeded the "
                f"{self.valves.MAX_BUFFER_MB} MiB `MAX_BUFFER_MB` limit — "
                "usually a very large file or image read into the transcript. "
                "Raise `MAX_BUFFER_MB` in the pipe's valves, or work with a "
                "smaller file.\n"
            )
        except Exception as exc:
            if resume_id and state.turn_session_id is None:
                # Resume died before the session came up. Drop the stale id
                # and rerun this turn cold — _render_transcript replays the
                # history, and the new session id gets persisted on init.
                log.warning(
                    "resume of %s failed (%s: %s); retrying cold",
                    resume_id, type(exc).__name__, exc,
                )
                if chat_id:
                    _chat_sessions.pop(chat_id, None)
                    _save_session_meta(
                        workdir_root, chat_id, {"cwd": str(cwd)}
                    )
                await emit_status("Session expired — replaying history…")
                async for chunk in self._pipe_stream(
                    body, __chat_id__, __event_emitter__, __files__,
                    __user__, __metadata__,
                    turn_info=turn_info, event_call=event_call, _no_resume=True,
                    inflight=inflight,
                ):
                    yield chunk
                return
            log.exception("Claude Agent SDK pipe failed")
            await emit_status(f"Error: {exc}", done=True)
            yield f"\n\n**Claude Code error:** `{type(exc).__name__}: {exc}`\n"
        finally:
            state.active_tools.clear()
            if heartbeat_task is not None and not heartbeat_task.done():
                heartbeat_task.cancel()
                try:
                    await heartbeat_task
                except asyncio.CancelledError:
                    pass
